### ISSUE TITLE
Breaking layout switch in sway

### ISSUE THREAD

**Issue by alghazanth** [alebastr/sway-systemd#26] opened 2023-07-22 12:31 UTC
After installation of version 0.4 hotkeys for keyboard layot switch ceased to work.  Part of sway config responsive for that functionality looks that:
```
input type:keyboard {
    xkb_layout us,ru
    xkb_options grp:rctrl_toggle,compose:ralt
}
```
Highly likely [this script](https://github.com/alebastr/sway-systemd/blob/main/src/locale1-xkb-config) is the cause. I dunno exactly which part of the logic of the script causes that, could you please check/verify somehow?

**Comment by alebastr** [comment] 2023-07-22 14:14
Yep, it's a known problem. That's why the script is not enabled by default and is not recommended to be used by default.
Apparently, AUR package maintainer thinks otherwise, but that's out of my control.

Duplicate of #21

**Closed by alebastr** 2023-07-22 14:14 UTC
