### ISSUE TITLE
Sway-session.target started before sway is ready

### ISSUE THREAD

**Issue by ibrokemypie** [alebastr/sway-systemd#10] opened 2021-10-27 04:50 UTC
I don't think this bug has been recently introduced by sway-systemd itself, most likely in some sway change, but the problem is still here. Recently the services attached to the sway-session target are being started before sway is ready, resulting in errors such as ``Exception: Failed to retrieve the i3 or sway IPC socket path`` and ``cannot open display: ``
Most of these issues cause the services to restart over and over until sway *is* ready, which is a bit annoying, and some don't restart at all and need to be restarted manually after sway has fully loaded.

Is there any way to delay starting the services attached to the sway-session target until sway has finished starting and is accepting connections?

**Comment by ibrokemypie** [comment] 2021-10-31 05:50
Actually they aren't like your example at all, they all look like this:
```
[Unit]
Description=Random background slideshow
BindsTo=sway-session.target

[Service]
Type=simple
ExecStart=/usr/bin/bash %h/.config/sway/bg.sh

[Install]
WantedBy=sway-session.target
```

Is this where the problem lies?

**Comment by alebastr** [comment] 2021-11-03 09:05
`BindsTo` is a stronger version of `Requires`, so if any of these services is started it will bring up `sway-session` and `graphical-session`. So that's a possibility, even if unlikely one.

If you don't mind doing a bit of debugging, you can do following:
1. change your sway launch command to `systemd-cat -t sway -- sway -d`
1. add `set -v` right after  the long comment header in `/usr/lib/sway-systemd/session.sh`
1. add `systemctl --user show-environment` right after `systemctl --user import-environment ...`
1. check that `systemctl --user is-active sway-session.target` is `inactive`
1. run sway
1. collect `journalctl --user -o short-monotonic --no-hostname --since=-2m` output (adjust --since as necessary)
1. Look through it, paying attention to what, when and with what environment is started.

At the moment of `[sway/config.c:667] Running deferred commands` all the necessary environment and sockets are ready. If anything triggers the target before that, you should at least see when systemd started it. If anything prevents the script from initializing the environment, you will see missing variables in the `show-environment` output.

**Comment by markstos** [comment] 2022-01-16 16:24
I recommend closing this because it appears to be a user environment issue, not a bug with this project.

**Comment by markstos** [comment] 2022-03-09 19:14
> Maybe there should be some warning in the documentation against systemctl commands in the config?

I agree. There's currently no documentation on the recommended way to start systemd services when using `sway-systemd`. The answer is to "enable" them them as you would other systemd user services, but this case it's worth documenting as Sway has it's own "usual" way of starting background services which as you found out is not necessarily the best way to start systemd services. 

A doc-patch would be welcome.

**Comment by alebastr** [comment] 2022-03-09 19:25
> The answer is to "enable" them them as you would other systemd user services

kanshi is a special case because of https://github.com/emersion/kanshi/issues/43. `exec_always` is the suggested way to get kanshi working after config reload.

We can suggest to place kanshi line after sway-systemd includes, but it will be prone to races anyways.

**Comment by markstos** [comment] 2022-03-09 22:32
Seems like Sway should emit a `reload` event like it does for `shutdown`. Services like Kanshi could then subscribe to `reload` and then reload themselves as well.

**Comment by nzig** [comment] 2022-03-10 08:09
> **Edit:** `exec_always systemctl --user try-reload-or-restart kanshi` should work around the kanshi issue. The command won't do anything if the service is not started.

Thanks, I'll try that. Why do you suggest `try-reload-or-restart` and not `try-restart`?

**Comment by alebastr** [comment] 2022-03-10 16:18
> Seems like Sway should emit a `reload` event like it does for `shutdown`. Services like Kanshi could then subscribe to `reload` and then reload themselves as well.

`kanshi` doesn't use Sway IPC. It relies on wlroots-specific wayland protocols, and there are no `reload` or `shutdown` events in these.

> Why do you suggest `try-reload-or-restart` and not `try-restart`?

There's no reason with released kanshi 1.2.0. But git snapshots have `kanshictl reload` and `SIGHUP` triggers for configuration reload. Either of those could be used in the systemd unit to reapply the config faster, e.g. `ExecReload=kanshictl reload`

**Comment by OJFord** [comment] 2022-04-09 21:13
I have the same issue as @nzig, but no `exec systemctl ...` in sway config - no `exec`s at all besides key bindings (that I'm not pressing on startup!).

I have no idea what's importing DISPLAY/SWAYSOCK/WAYLAND_DISPLAY, it's not 'me' or something I've deliberately configured - any tips for tracking it down?

Do we really need to check if the variables are already set here anyway, isn't it enough that the session target isn't active to indicate that it should be started?

**Comment by rylee-randall** [comment] 2022-05-07 03:50
I finally ended up finding the answer! (In my case at least)

Arch includes a /etc/sway/config.d/50-systemd-user.conf file with the following contents, which when all commented out, makes sway-systemd work on login again!

```
# sway does not set DISPLAY/WAYLAND_DISPLAY in the systemd user environment
# See FS#63021
# Adapted from xorg's 50-systemd-user.sh, which achieves a similar goal.

exec systemctl --user import-environment DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP
exec hash dbus-update-activation-environment 2>/dev/null && \
     dbus-update-activation-environment --systemd DISPLAY WAYLAND_DISPLAY SWAYSOCK XDG_CURRENT_DESKTOP

```

**Comment by mkhl** [comment] 2022-05-12 06:42
sway forks processes for each `exec` found while reading its configuration, and session.sh ends up racing the commands from arch `50-systemd-user.conf`

would it make sense to split session.sh into two scripts, one that sets variables in the systemd environment and one that starts sway-session.target? that should at least mitigate the case where

> Another session found; refusing to overwrite the variables

prevents the session from starting

**Comment by alebastr** [comment] 2022-05-13 03:37
Fixed in https://github.com/alebastr/sway-systemd/commit/eccaf4a54cfd962774c96a5017d24693ec5ce72f.

Variable check was the simplest way to detect all the nested configurations (Sway on Gnome or KDE or any X11 WM) without explicitly testing for each and every compositor either via pgrep or with a specific target name. But the code snippet above is too widespread and even if it wasn't a part of the default config on Arch, too many people already have it in their configs.

I might reintroduce the variable test again once I figure out how to avoid this problem (I mean I already know how, but making it look simple and readable in a posix shell dialect is another problem).

> Arch includes a /etc/sway/config.d/50-systemd-user.conf file with the following contents, which when all commented out, makes sway-systemd work on login again!

Thanks for finding this! I forgot that Arch installs that file, and the issue made no sense to me until you mentioned it.

> would it make sense to split session.sh into two scripts, one that sets variables in the systemd environment and one that starts sway-session.target? that should at least mitigate the case where

Not really. The commands have to be run in a sequence. If you split the scripts, you'll get another race where `sway-session.target` may start before the variables are exported.

**Closed** 2023-05-21 19:21 UTC
